version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: <your-database>
      POSTGRES_USER: <your-user>
      POSTGRES_PASSWORD: <your-password>
    networks:
      - <your-network>

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres
      DB_PORT: 5432
      DB_NAME: <your-database>
      DB_USERNAME: <your-user>
      DB_PASSWORD: <your-password>
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - <your-network>

networks:
  <your-network>:
    driver: bridge
