version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: vanja
      POSTGRES_PASSWORD: vanja123
    networks:
      - reservationApp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres
      DB_PORT: 5432
      DB_NAME: reservations
      DB_USERNAME: vanja
      DB_PASSWORD: vanja123
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - reservationApp-network

networks:
  reservationApp-network:
    driver: bridge
